### ISSUE TITLE
Modul "Katalog" - Ausgabe aller Artikel einer Kategorie

### ISSUE THREAD

**Issue by medienschmiede71** [dtpop/warehouse#3]
1) Befinden sich in einer Kategorie mehrere Artikel wird nur der erste komplett ausgegeben. Für die weiteren Artikel wird kein Titel und keine Beschreibung ausgegeben. Der Preis und der "In den Warenkorb"-Button schon.

2) Die Mengenerhöhung, bzw. Reduzierung über die + und - ist ohne Funktion.

![Bildschirmfoto 2019-07-22 um 11 06 05](https://user-images.githubusercontent.com/6106333/61620337-f815be80-ac70-11e9-9711-51874d4c8c5d.png)

**Comment by dtpop** [comment]
Danke für die Info @medienschmiede71 
Die Möglichkeiten und die Anforderungen an eine Ausgabe sind sehr vielfältig und komplex.
Die Datenstruktur ist angelegt auf mehrstufige Kategorien, Artikel, Varianten und Artikel mit Attributen.
Momentan überschreitet es meine Kapazität für jeden Usecase ein Fragment mit passendem Ausgabemodul zu schreiben. Eine neue installierbare Demo ist jedoch in Arbeit.
Gleiches gilt für die -/+ Buttons. Vielleicht möchte jemand an dieser Stelle ein Select haben.
Der jQuerycode, damit die +/- Buttons funktionieren wäre z.B.

```
$(function () {    
    
    $('label.switch_count').click(function() {
        var for_id = $(this).attr('for');
        var cur_val = $('input#'+for_id).val();
        var new_val = eval(cur_val + $(this).data('value'));
        if (new_val < 1) {
            new_val = 1;
        }
        $('input#'+for_id).val(new_val);
    }); 

});
```
Eine funktionsfähige installierbare Demo ist in Arbeit.
