### ISSUE TITLE
Anzahl Input nimmt alle Werte entgegen

### ISSUE THREAD

**Issue by eaCe** [dtpop/warehouse#5]
Alle nicht-Numerischen Eingaben fügen einen Artikel in den Warenkorb hinzu.
Es wäre vielleicht Sinnvoll dem Input die passenden Attribute zu geben:
`inputmode="numeric" type="number"`

![grafik](https://user-images.githubusercontent.com/2708231/62473486-1f0bde80-b7a1-11e9-8254-741d36ee81fe.png)

**Comment by dtpop** [comment]
Danke für die Idee. type="number" sieht allerdings optisch sehr unschön aus wenn zusätzlich zu den (gewollten) großen +/- Buttons noch Pfeile im Inputfeld erscheinen. Da das Feld in den Fragmenten steht und die Fragmente eh zur individuellen Anpassung gedacht sind, verzichte ich zunächst mal auf die Umsetzung.
